### ISSUE TITLE
Have participated with my ENS address before EOD of April 17th but i are not in this tweetdrop list

### ISSUE THREAD

**Issue by seeyou777** [nation3/nation-drop#1]
Have participated with my ENS address before EOD of April 17th but i are not in this tweetdrop list.
Here is the link to the tweet I retweeted：https://twitter.com/Nation3DAO/status/1512472974921814017

My ENS address: 12hour.eth

Also I have added photographic proof, please check the attachment, thanks！
![11](https://user-images.githubusercontent.com/97087733/164066537-9f2fd457-f434-4a09-97a8-30346749ad2d.png)
![12](https://user-images.githubusercontent.com/97087733/164066573-6667c357-f299-4345-bf47-18ad6bfab44b.png)

**Comment by luisivan** [comment]
Please send via email and we'll check! https://twitter.com/Nation3DAO/status/1516449549509931019?s=20&t=FltOIMd-uGFsOajD9HMQJw
