### ISSUE TITLE
I have participated with my ENS address before EOD of April 17th but I am not in this tweetdrop list, plz check it for me,tks a lot.

### ISSUE THREAD

**Issue by Wenser2010** [nation3/nation-drop#2]
The evidence is here. And tks for ur patience and recheck.

https://twitter.com/wenser2010/status/1513336881869590532?s=20&t=VzsEfj-jy8r5i_j6HMIsew

![image](https://user-images.githubusercontent.com/100747320/164168694-0306e723-934d-42b3-8e21-c5f2af243626.png)

**Comment by luisivan** [comment]
Please send via email and we'll check! https://twitter.com/Nation3DAO/status/1516449549509931019?s=20&t=FltOIMd-uGFsOajD9HMQJw

**Comment by Wenser2010** [comment]
> 

gotcha，tks，Luisivan

**Comment by Wenser2010** [comment]
> 

but how abt the email address? tweetdrop@nation3.org is wrong.
